### ISSUE TITLE
PCB整體長度

### ISSUE THREAD

**Issue by Mamashu** [Sucareto/Arduino-Chunithm-Controller#3]
你好,最近正在研究你給出的PCB設計圖和壓克力,未來有想要去訂製並且來做一個手台,但看完Arduino Pro Micro的那些的位置,還是不確定PCB整體是幾X幾的,所以想來請教一下

**Comment by Sucareto** [comment]
使用立创EDA打开PCB，检查边框信息，就可以看到。
我的PCB尺寸是480mm x 170mm。

**Comment by Mamashu** [comment]
那我還想在問一下,PB1~6是接紅外線接收元件嗎,A0~A3是發射元件嗎,如果是的話還少2個發射元件的位置是要怎麼接呢,目前是紅外線的這一段看不太懂要怎麼接,還麻煩幫忙解惑一下,非常感謝

**Comment by Sucareto** [comment]
我记得PCB里面有标注，左上角的是发射端，pro micro孔位右边的4个方框是按钮，右上角的是air接收端。
发射端不需要控制，只要接5V和GND就好了。
这个红外方案并不好用，建议改掉。

**Comment by Mamashu** [comment]
那A0~A3和RST做成按鈕的用途是做什麼的，這邊也看不太懂，因為RST是讓整個Arduino重製，主要是怕程式出問題需要重製才這樣做的嗎，然後按鈕是用零件名稱能麻煩一下嗎，因為目前看到都3pin或4pin的，沒有看到2pin的按鈕元件

**Comment by Sucareto** [comment]
开关搜索关键词“8*8 轻触开关 硅胶 2脚”，如果没找到，你也可以修改PCB。
RST用于重启开发板进入上传模式，另外4个按键可以自定义用途，如果不需要可以删掉。
默认定义的是F1=test，F2=service，F3=coin，Enter=刷卡
