### ISSUE TITLE
请问air的pcb要如何绘制以连接slide部分？

### ISSUE THREAD

**Issue by MrRaiko3** [Sucareto/Arduino-Chunithm-Controller#5]
以及此版本只有16key吗？pcb看起来是只有16k的样子，还有许多的5v/3.3v口我有点不理解接法，求教

**Comment by MrRaiko3** [comment]
以及ws2812b的焊点我好像没找到。。。

**Comment by Sucareto** [comment]
这个方案已经过时了，当时是只考虑了16key的，之后没有继续研究了。
air部分是没有pcb的，是通过x2.54接口的线缆直连到PCB上。
ws2812b部分，是把灯带贴到pcb上，用铜丝连接到pcb左侧的孔位。
总之这个pcb方案已经是非常过时且不推荐使用了，可以看下以下的方案：
https://bemani.cc/d/102-chunithm
https://bemani.cc/d/92-chunithm800-1000cnychunicon

**Comment by MrRaiko3** [comment]
> 这个方案已经过时了，当时是只考虑了16key的，之后没有继续研究了。
> air部分是没有pcb的，是通过x2.54接口的线缆直连到PCB上。
> ws2812b部分，是把灯带贴到pcb上，用铜丝连接到pcb左侧的孔位。
> 总之这个pcb方案已经是非常过时且不推荐使用了，可以看下以下的方案：
> https://bemani.cc/d/102-chunithm
> https://bemani.cc/d/92-chunithm800-1000cnychunicon

感谢您的指点与帮助，让我受益匪浅了
