### ISSUE TITLE
大佬您好，再次请教一下

### ISSUE THREAD

**Issue by MrRaiko3** [Sucareto/Arduino-Chunithm-Controller#6]
我想用红外灯珠来实现air的感应部分，在只用这一块开发版的条件下该怎么做？是在现有代码基础上修改吗？（kb874的体积以及飞线有点繁琐，于是我便用两块pcb版上用940nm红外收发灯珠模拟信号实现air检测，但没有相关资料不知道怎么做，太笨了）

air部分附图如下。

此外，pcb版上有许多接口我还没用到，有点不明白，比如中间的两个电源输出，以及角落和左上角的接口都有什么用？（如果您能留下一个联系方式那是再好不过了，因为我不清楚您是使用什么平台作联系，我只能在这里等待您的回复）

恳请不吝赐教，指点迷津（话说真的是东除我佬啊）
![mmexport1666274869342.jpg](https://user-images.githubusercontent.com/92285459/197008692-f7e092b8-8fae-432d-baf8-4c5f2bf4a043.jpg)

**Comment by Sucareto** [comment]
在 [KeyCheck()](https://github.com/Sucareto/Arduino-Chunithm-Controller/blob/master/ChuniSerialController/slider_cmd.h#L217) 函数内已经实现了 AIR 的检测和发送。
实现方式是：
左侧的 6 个 VCC 和 GND 接到发射端的红外灯珠，右侧的接到接收端的，其中`PB1 ~ PB6`是数据引脚，用于读取接收端灯珠输出的数字信号，程序会对这部分数据进行处理后发送给主机。
中间的两个电源接口，是用于安装`AMS1117 5V 转 3.3V 模块`的，因为使用的主控都是 5V 输出，而 MPR121 模块需要 3.3V 电源输入，这个我有在 PCB 上面标注。

如果还需详细讨论，可以通过 Discord 联系`Sucareto#2440`。
或者，可以留下你方便使用的联系方式。

**Comment by Sucareto** [comment]
已通过 QQ 联络。
关于 MPR121 的 I2C 地址修改，我在 PCB 设计的时候有考虑到这个问题，所以在 MPR121 上面多留了一排孔用于接线。
地址的定义：
```
ADD 未连接或接 GND: 0x5A
ADD 接到 3.3V: 0x5B
ADD 接到 SDA: 0x5C
ADD 接到 SCL: 0x5D
```
具体可以参考[MPR121 手册](https://files.seeedstudio.com/wiki/Grove-I2C_Touch_Sensor/res/Freescale_Semiconductor;MPR121QR2.pdf)的 21 页。
在中国大陆内买到的 MPR121，大部分是 ADD 短接到了 GND 上，需要小心的切断短接的线，然后重新接到其他脚，就可以改变地址。
